apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
data:
  username: aW90dXNlcg==  # base64 encoded 'iotuser'
  password: cG9zdGdyZXNwYXNzd29yZA==  # base64 encoded 'postgrespassword'
type: Opaque
